pod 'BaiduMapAPI', '~> 2.8.1'
pod 'AFNetworking', '~> 2.6.0'
pod 'Masonry', '~> 0.6.2'
pod 'ReactiveCocoa', '~> 2.5'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MJRefresh'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.3'
pod 'SFHFKeychainUtils', '~> 0.0.1'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJExtension', '~> 3.0.7'
pod 'UMengAnalytics'